version: '3.8'
services:
  web:
    build: .
    environment:
      - GOFLAGS=-buildvcs=false
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: air buildvcs=false cmd/main.go  -b 0.0.0.0 
